[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"
dockerContext = "./"

[deploy]
# CMD in Dockerfile starts the Next.js server
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
